# pcr_lib.pyi
from typing import List

class snp_data:
    rsid: str
    allele: str
    primer_sequence: str
    direction: str
    length: int
    gc_content: str
    hairpin: str
    homodimer: str

    def __getitem__(self, key: str) -> str: ...

class snp_array:
    data: List[snp_data]

    def __getitem__(self, index: int) -> snp_data: ...

def reverse_complement(s: str) -> str: ...
def generate_allele_spesific_primers(data: snp_data, min_length: int, max_length: int) -> snp_array: ...
def introduce_missmatch(s: str, pos: int) -> List[str]: ...
def filter_primers(data: snp_data, tm_min: int, tm_max: int, hairpin_max: float, homodimer_max: float) -> snp_array: ...
def rank_primers(data: snp_array) -> snp_array: ...
def generate_matching_primers(data: snp_array, allele_specific_primers: snp_array, min_distance: int, max_distance: int) -> snp_array: ...
def check_multiplex_compatibility(data: snp_array, heterodimer_max: float) -> snp_array: ...
