# pcr_lib.pyi
from typing import List

class primer:
    rsid: str
    allele: str
    primer_sequence: str
    direction: str
    length: int
    gc_content: str
    hairpin: str
    homodimer: str

    def __getitem__(self, key: str) -> str: ...

class primer_group:
    data: List[primer]

    def __getitem__(self, index: int) -> primer: ...

def reverse_complement(s: str) -> str: ...
def generate_allele_spesific_primers(data: primer, min_length: int, max_length: int) -> primer_group: ...
def introduce_missmatch(s: str, pos: int) -> List[str]: ...
def filter_primers(data: primer, tm_min: int, tm_max: int, hairpin_max: float, homodimer_max: float) -> primer_group: ...
def rank_primers(data: primer_group) -> primer_group: ...
def generate_matching_primers(data: primer_group, allele_specific_primers: primer_group, min_distance: int, max_distance: int) -> primer_group: ...
def check_multiplex_compatibility(data: primer_group, heterodimer_max: float) -> primer_group: ...
