from Bio import Seq

snp = 'ATGCAATTGGCCAAATTTGGGCCCAAAATTTTGGGGCCCCAAAAATTTTTGGGGGCCCCCAAAAAATTTTTTGGGGGGCCCCCC'
# max_len = 30
# min_len = 18
# for length in range(max_len-min_len-1):
#     trimmed = snp[length]
#     print(trimmed)
#     print(length)


# ABCDEFGHIJKLMNOPQRSTUVWXYZ 2A2B2C2D2E2F2G2H2I2J2K
# ABCDEFGHIJKLMNOPQRSTUVWXYZ 2A2B2C2D2E2F2G2H2I2J2
# ABCDEFGHIJKLMNOPQRSTUVWXYZ 2A2B2C2D2E2F2G2H2I2J
# ABCDEFGHIJKLMNOPQRSTUVWXYZ 2A2B2C2D2E2F2G2H2I2
# ABCDEFGHIJKLMNOPQRSTUVWXYZ 2A2B2C2D2E2F2G2H2I
# ABCDEFGHIJKLMNOPQRSTUVWXYZ 2A2B2C2D2E2F2G2H2
# ABCDEFGHIJKLMNOPQRSTUVWXYZ 2A2B2C2D2E2F2G2H
# ABCDEFGHIJKLMNOPQRSTUVWXYZ 2A2B2C2D2E2F2G2
# ABCDEFGHIJKLMNOPQRSTUVWXYZ 2A2B2C2D2E2F2G
# ABCDEFGHIJKLMNOPQRSTUVWXYZ 2A2B2C2D2E2F2
# ABCDEFGHIJKLMNOPQRSTUVWXYZ 2A2B2C2D2E2F
# ABCDEFGHIJKLMNOPQRSTUVWXYZ 2A2B2C2D2E2
# ABCDEFGHIJKLMNOPQRSTUVWXYZ 2A2B2C2D2E

snp_short = snp[0:10]
print(f"Normal string: {snp_short}")
seq = Seq.Seq(snp_short)
print(f"Now a sequence in BIO Python: {seq}")
reverse = seq.reverse_complement()
print(f"Now a reverse sequence in Bio Python: {reverse}")
rev_string = str(reverse)
print(f"Now a string again: {rev_string}")
reverse